name: Create Release with PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename and Upload PDF to Release
        run: |
          cp pdf/sl.pdf songbook.pdf
          gh release upload ${{ github.ref_name }} songbook.pdf --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
